#pragma once

#include <iostream>
#include <cstdio>
#include <memory>
#include <stdexcept>
#include <string>
#include <array>
#include <vector>
#include <functional>
#include <chrono>
#include <future>
#include <cstdio>
#include <sstream>
#include <mutex>
#include <bits/stdc++.h> 
#include <curses.h>
#include <menu.h>
#include <form.h>